image: Visual Studio 2019
version: 1.0.{build}
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
environment:
  CODECOV_REPO_TOKEN:
    secure: oC0OUIZSVY7kLUnkWIw33aVZrTkJIeNhFGM/fy2WYvFgdG+GeajLvF+UeGHYXEfF
configuration:
  - Release
test_script:
  - ps: |
      dotnet test --configuration Release --filter=TestCategory!=ApiTests /p:CollectCoverage=true /p:Exclude='\"[*TestAdapter*]*,[*]*.Startup*,[*]*.Program,[*.Test*]*,[nunit*]*\"' /p:ExcludeByAttribute='\"Obsolete,GeneratedCode,CompilerGeneratedAttribute\"'  /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../coverage/Fluent.Net.coverage.cobertura.xml /p:Threshold=80 /p:ThresholdType=branch Fluent.Net.Test/Fluent.Net.Test.csproj
      dotnet test --configuration Release --filter=TestCategory!=ApiTests /p:CollectCoverage=true /p:Exclude='\"[*TestAdapter*]*,[*]*.Startup*,[*]*.Program,[*.Test*]*,[nunit*]*,[Fluent.Net]*\"' /p:ExcludeByAttribute='\"Obsolete,GeneratedCode,CompilerGeneratedAttribute\"'  /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../coverage/Fluent.Net.SyntaxTest.coverage.cobertura.xml /p:Threshold=80 /p:ThresholdType=branch Fluent.Net.SyntaxTest.Test/Fluent.Net.SyntaxTest.Test.csproj
after_test:
- ps: |
    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    $env:PATH = 'C:\Program Files\git\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f '"coverage/*.xml"' -t $env:CODECOV_REPO_TOKEN
for:
-
  branches:
    only:
      - master

  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: lo9gC4NDoECBxAzgZZMFKklAQGmyL7VOIfMzPqRB1InlB4D5g4A+tSGUITR2pS6i
    skip_symbols: false
